### ISSUE TITLE
Small one

### ISSUE THREAD

**Issue by ldutoit** [colin-olito/XvAutosomeInversions#8]
Not 100% sure but:

line 446 of  functions WFSims-autosomal in runReplicateAutoInvSims, it runs:

		 `repRes  <-  autoInvFwdSim(Fii.init=Fii.init, N=N, W=W, m=m, r=r)`

It could probably include the savetrajectories argument like this

		`repRes  <-  autoInvFwdSim(Fii.init=Fii.init, N=N, W=W, m=m, r=r,saveTrajectories=saveTrajectories)`

**Comment by colin-olito** [comment]
You are right! I'm missing the saveTrajectories argument there! Thanks for catching that - will fix!
